# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'IntercomTesting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Intercom'

end
